Pandas：63~82

## 11.Pandas
### ■ 64. データの読み込み

`weather.csv`を読み込み、`df` で定義してください。

（目安時間：1分）

In [21]:
import pandas as pd
df = pd.read_csv("weather.csv")
df

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
0,NaN,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,...,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号,NaN,品質情報,均質番号
1,2019/12/14,9.3,8,1,15.9,8,1,3.2,8,1,...,1,NaN,0,1,2.0,8,1,8.9,8,1
2,2019/12/15,7.8,8,1,11.1,8,1,4.0,8,1,...,1,NaN,0,1,2.3,8,1,6.3,8,1
3,2019/12/16,6.9,8,1,12.5,8,1,1.3,8,1,...,1,NaN,0,1,1.1,8,1,8.9,8,1
4,2019/12/17,8.2,8,1,10.3,8,1,5.7,8,1,...,1,NaN,0,1,1.1,8,1,0.2,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2020/12/10,8.7,8,1,11.1,8,1,6.0,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
364,2020/12/11,9.2,8,1,13.8,8,1,3.5,8,1,...,1,NaN,0,1,0.8,8,1,4.3,8,1
365,2020/12/12,10.4,8,1,14.0,8,1,8.0,8,1,...,1,NaN,0,1,1.4,8,1,1.4,8,1
366,2020/12/13,8.6,8,1,14.4,8,1,4.4,8,1,...,1,NaN,0,1,1.0,8,1,5.5,8,1
367,2020/12/14,7.8,8,1,12.2,8,1,4.4,8,1,...,1,NaN,0,1,1.9,8,1,4.4,8,1

### ■ 65. データの中身確認

読み込んだデータ`df`の先頭3行、末尾10行を表示してください。

（目安時間：1分）

In [22]:
df.head(3)
df.tail(10)

,年月日,平均気温(℃),平均気温(℃).1,平均気温(℃).2,最高気温(℃),最高気温(℃).1,最高気温(℃).2,最低気温(℃),最低気温(℃).1,最低気温(℃).2,...,平均雲量(10分比).2,平均蒸気圧(hPa),平均蒸気圧(hPa).1,平均蒸気圧(hPa).2,平均風速(m/s),平均風速(m/s).1,平均風速(m/s).2,日照時間(時間),日照時間(時間).1,日照時間(時間).2
358,2020/12/5,6.0,8,1,7.3,8,1,4.3,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
359,2020/12/6,8.0,8,1,13.3,8,1,4.5,8,1,...,1,NaN,0,1,1.0,8,1,3.8,8,1
360,2020/12/7,9.0,8,1,16.0,8,1,4.2,8,1,...,1,NaN,0,1,0.7,8,1,9.0,8,1
361,2020/12/8,10.4,8,1,16.0,8,1,4.6,8,1,...,1,NaN,0,1,1.3,8,1,6.9,8,1
362,2020/12/9,9.2,8,1,11.2,8,1,8.3,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
363,2020/12/10,8.7,8,1,11.1,8,1,6.0,8,1,...,1,NaN,0,1,1.4,8,1,0.0,8,1
364,2020/12/11,9.2,8,1,13.8,8,1,3.5,8,1,...,1,NaN,0,1,0.8,8,1,4.3,8,1
365,2020/12/12,10.4,8,1,14.0,8,1,8.0,8,1,...,1,NaN,0,1,1.4,8,1,1.4,8,1
366,2020/12/13,8.6,8,1,14.4,8,1,4.4,8,1,...,1,NaN,0,1,1.0,8,1,5.5,8,1
367,2020/12/14,7.8,8,1,12.2,8,1,4.4,8,1,...,1,NaN,0,1,1.9,8,1,4.4,8,1

### ■ 66. 不要な列、行の削除

行は先頭のみ、列は、カラム名（列名）が「〇〇.1」「〇〇.2」となっているものを削除したDataFrame `df` を再定義してください。

（目安時間：5分）

In [25]:
df.columns

Index(['年月日', '平均気温(℃)', '平均気温(℃).1', '平均気温(℃).2', '最高気温(℃)', '最高気温(℃).1',
       '最高気温(℃).2', '最低気温(℃)', '最低気温(℃).1', '最低気温(℃).2', '降水量の合計(mm)',
       '降水量の合計(mm).1', '降水量の合計(mm).2', '最深積雪(cm)', '最深積雪(cm).1', '最深積雪(cm).2',
       '平均雲量(10分比)', '平均雲量(10分比).1', '平均雲量(10分比).2', '平均蒸気圧(hPa)',
       '平均蒸気圧(hPa).1', '平均蒸気圧(hPa).2', '平均風速(m/s)', '平均風速(m/s).1',
       '平均風速(m/s).2', '日照時間(時間)', '日照時間(時間).1', '日照時間(時間).2'],
      dtype='object')

In [31]:
df = df[['年月日', '平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '最深積雪(cm)', 
       '平均雲量(10分比)', '平均蒸気圧(hPa)', '平均風速(m/s)','日照時間(時間)']][2:]

df.head()

,年月日,平均気温(℃),最高気温(℃),最低気温(℃),最深積雪(cm),平均雲量(10分比),平均蒸気圧(hPa),平均風速(m/s),日照時間(時間)
3,2019/12/16,6.9,12.5,1.3,NaN,NaN,NaN,1.1,8.9
4,2019/12/17,8.2,10.3,5.7,NaN,NaN,NaN,1.1,0.2
5,2019/12/18,9.9,15.0,4.8,NaN,NaN,NaN,1.2,4.3
6,2019/12/19,8.6,9.7,7.9,NaN,NaN,NaN,1.3,0.0
7,2019/12/20,10.1,15.8,5.7,NaN,NaN,NaN,1.5,9.0

### ■ 67. DataFrameに関する情報の取得

下記の値を取得してください。

- 各列のデータ型
- DataFrameのサイズ
- 列名
- 行名

（目安時間：2分）

In [34]:
df.dtypes

年月日            object
平均気温(℃)       float64
最高気温(℃)       float64
最低気温(℃)       float64
最深積雪(cm)      float64
平均雲量(10分比)    float64
平均蒸気圧(hPa)    float64
平均風速(m/s)     float64
日照時間(時間)      float64
dtype: object

In [36]:
df.shape

(365, 9)

In [38]:
df.columns

Index(['年月日', '平均気温(℃)', '最高気温(℃)', '最低気温(℃)', '最深積雪(cm)', '平均雲量(10分比)',
       '平均蒸気圧(hPa)', '平均風速(m/s)', '日照時間(時間)'],
      dtype='object')

In [39]:
df.index

RangeIndex(start=3, stop=368, step=1)

### ■ 68. 任意の要素を取得

`df`の 5〜10行目, 3〜6列目（最高気温(℃)〜最深積雪(cm)）の要素を取得してください。


（目安時間：2分）

In [40]:
df.iloc[4:10,2:6]

    最高気温(℃)  最低気温(℃)  最深積雪(cm)  平均雲量(10分比)
7      15.8      5.7       NaN         NaN
8       8.4      6.5       NaN         NaN
9       9.8      4.2       NaN         NaN
10     12.1      3.6       NaN         NaN
11     12.1      4.1       NaN         NaN
12      7.9      2.5       NaN         NaN

### ■ 69. 条件抽出

`people.csv` を読み込み`df_people`と定義してください。

その後、下記の条件を満たすDataFrameをそれぞれ抽出してください。

- `nationality` が `America` である
- `age` が 20以上30未満である

（目安時間：3分）

In [43]:
df_people = pd.read_csv("people.csv")
df_people

   age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
2   35  31    Suzuki       Japan
3   16  20      John     America
4   28  11       Kim       Korea

In [46]:
df_people[df_people["nationality"] == "America"]

   age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [50]:
df_people.query('nationality == "America"')

   age  id  name nationality
1   21  33  Mike     America
3   16  20  John     America

In [52]:
df_people[(df_people["age"] >= 20 ) & (df_people["age"] <= 30)]

   age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

### ■ 70. ユニークな値の抽出

`df_people`に対して、カラム毎のユニーク（固有）な値を抽出してください。

（目安時間：2分）

In [54]:
df_people["nationality"].unique()

array(['Japan', 'America', 'Korea'], dtype=object)

In [55]:
df_people.drop_duplicates(subset="natio")

   age  id      name nationality
0   26  13  Imanishi       Japan
1   21  33      Mike     America
4   28  11       Kim       Korea

Index(['age', 'id', 'name', 'nationality'], dtype='object')

### ■ 73. 並び替え

`df`を最高気温が高い順に並び替えてください。

（目安時間：2分）

### ■ 74. ダミーデータへの処理

`df_people`の`nationality`カラムをダミー変数に変換してください。

（目安時間：2分）

### ■ 75. 欠損値の確認

`df`の欠損値を確認してください。

（目安時間：1分）

### ■ 76. 欠損値の補完

`df`の欠損値を全て0で補完してください。

（目安時間：1分）

### ■ 77. 欠損値の削除

`df`の欠損値を列方向で削除してください。

（目安時間：1分）

### ■ 78. ユニークな値と出現回数

`iris.csv`を読み込み`df_iris`と定義してください。

その後、`df_iris`の`Class`カラムにおいて、ユニークな値とその出現回数を確認してください。

（目安時間：2分）

### ■ 79. グループごとの集計

`df_iris`の下記各クラスにおける`sepal-length`, `sepal-width`, `petal-length`, `petal-width`の平均値を求めてください。

- Iris-setosa
- Iris-versicolor
- Iris-virginica

（目安時間：4分）

### ■ 80. 統計量の確認

`df_iris`の各カラムにおける、下記統計量を算出してください。

- 平均値
- 中央値
- 標準偏差
- 最大値
- 最小値

（目安時間：3分）

### ■ 81. 折れ線グラフの表示

`df`の先頭50日間おける平均気温、最高気温、最低気温を折れ線グラフ（凡例なし）で可視化してください。  
※横軸は`年月日`とすること

（目安時間：4分）

### ■ 82. 相関係数の算出

`df`の下記3項目同士の相関係数を算出してください。

- 平均気温
- 降水量の合計
- 日照時間

（目安時間：3分）

### ■ 83. データの出力

欠損値を0で補完した`df`を`export.csv`というファイル名でcsvとして出力してください。インデックスの出力は不要です。

（目安時間：1分）